// import type { DisconnectionRecord } from "@/types/disconnection"

// // Mock data based on the table structure in the images
// export const mockDisconnectionData: DisconnectionRecord[] = [
//   {
//     id: "1",
//     date: "2025-05-20",
//     time: "22:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "B",
//     dc: true,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "2",
//     date: "2025-05-28",
//     time: "23:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "B",
//     dc: true,
//     rc: true,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "3",
//     date: "2025-05-28",
//     time: "0:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "B",
//     dc: false,
//     rc: true,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "4",
//     date: "2025-05-28",
//     time: "1:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "B",
//     dc: false,
//     rc: false,
//     payment100: true,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "5",
//     date: "2025-05-28",
//     time: "2:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "B",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: true,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "6",
//     date: "2025-05-28",
//     time: "3:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: true,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "7",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: true,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "8",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: true,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "9",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: true,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "10",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: true,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "11",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: true,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "12",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "C",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: true,
//     objections: false,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "13",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "D",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: true,
//     stoppedByNWSDB: false,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
//   {
//     id: "14",
//     date: "2025-05-28",
//     time: "4:22",
//     accountNo: "XXXXXX",
//     area: "Kalaniya",
//     supervisor: "A",
//     teamNo: "1",
//     helper: "D",
//     dc: false,
//     rc: false,
//     payment100: false,
//     payment80: false,
//     payment50: false,
//     alreadyPaid: false,
//     unSolvedCusComp: false,
//     gateClosed: false,
//     meterRemoved: false,
//     alreadyDisconnected: false,
//     wrongMeter: false,
//     billingError: false,
//     cantFind: false,
//     objections: false,
//     stoppedByNWSDB: true,
//     photo: "/placeholder.svg?height=100&width=100",
//   },
// ]

export const mockDisconnectionData = [
  {
    "id": "1",
    "date": "2025-06-02",
    "time": "00:00",
    "accountNo": "ACC1000",
    "area": "Galle",
    "supervisor": "D",
    "teamNo": "2",
    "helper": "D",
    "dc": true,
    "rc": false,
    "payment100": false,
    "payment80": true,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "2",
    "date": "2025-06-02",
    "time": "00:15",
    "accountNo": "ACC1001",
    "area": "Galle",
    "supervisor": "A",
    "teamNo": "4",
    "helper": "C",
    "dc": true,
    "rc": false,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": true,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": false,
    "billingError": true,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "3",
    "date": "2025-06-02",
    "time": "00:30",
    "accountNo": "ACC1002",
    "area": "JaEla",
    "supervisor": "D",
    "teamNo": "2",
    "helper": "C",
    "dc": false,
    "rc": true,
    "payment100": true,
    "payment80": true,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "4",
    "date": "2025-06-02",
    "time": "00:45",
    "accountNo": "ACC1003",
    "area": "Galle",
    "supervisor": "D",
    "teamNo": "1",
    "helper": "D",
    "dc": true,
    "rc": false,
    "payment100": true,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": true,
    "wrongMeter": true,
    "billingError": false,
    "cantFind": true,
    "objections": false,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "5",
    "date": "2025-06-02",
    "time": "01:00",
    "accountNo": "ACC1004",
    "area": "Kurunagala",
    "supervisor": "A",
    "teamNo": "1",
    "helper": "B",
    "dc": true,
    "rc": false,
    "payment100": true,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": false,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "6",
    "date": "2025-05-28",
    "time": "01:15",
    "accountNo": "ACC1005",
    "area": "Galle",
    "supervisor": "A",
    "teamNo": "4",
    "helper": "B",
    "dc": false,
    "rc": true,
    "payment100": false,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": true,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "7",
    "date": "2025-05-28",
    "time": "01:30",
    "accountNo": "ACC1006",
    "area": "JaEla",
    "supervisor": "B",
    "teamNo": "1",
    "helper": "C",
    "dc": false,
    "rc": true,
    "payment100": false,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": true,
    "billingError": true,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "8",
    "date": "2025-05-28",
    "time": "01:45",
    "accountNo": "ACC1007",
    "area": "Kurunagala",
    "supervisor": "C",
    "teamNo": "4",
    "helper": "B",
    "dc": false,
    "rc": true,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "9",
    "date": "2025-05-28",
    "time": "02:00",
    "accountNo": "ACC1008",
    "area": "Galle",
    "supervisor": "B",
    "teamNo": "2",
    "helper": "E",
    "dc": false,
    "rc": true,
    "payment100": true,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "10",
    "date": "2025-05-28",
    "time": "02:15",
    "accountNo": "ACC1009",
    "area": "Galle",
    "supervisor": "D",
    "teamNo": "2",
    "helper": "C",
    "dc": false,
    "rc": true,
    "payment100": true,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": true,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": false,
    "billingError": true,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "11",
    "date": "2025-05-28",
    "time": "02:30",
    "accountNo": "ACC1010",
    "area": "Galle",
    "supervisor": "A",
    "teamNo": "2",
    "helper": "E",
    "dc": false,
    "rc": false,
    "payment100": true,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": true,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "12",
    "date": "2025-05-28",
    "time": "02:45",
    "accountNo": "ACC1011",
    "area": "Galle",
    "supervisor": "D",
    "teamNo": "4",
    "helper": "D",
    "dc": false,
    "rc": false,
    "payment100": false,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": true,
    "billingError": false,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "13",
    "date": "2025-05-28",
    "time": "03:00",
    "accountNo": "ACC1012",
    "area": "Galle",
    "supervisor": "C",
    "teamNo": "4",
    "helper": "E",
    "dc": false,
    "rc": true,
    "payment100": true,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": true,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "14",
    "date": "2025-05-28",
    "time": "03:15",
    "accountNo": "ACC1013",
    "area": "Galle",
    "supervisor": "C",
    "teamNo": "1",
    "helper": "B",
    "dc": false,
    "rc": false,
    "payment100": false,
    "payment80": true,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": true,
    "billingError": true,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "15",
    "date": "2025-05-28",
    "time": "03:30",
    "accountNo": "ACC1014",
    "area": "Galle",
    "supervisor": "A",
    "teamNo": "4",
    "helper": "D",
    "dc": false,
    "rc": false,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": true,
    "billingError": true,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "16",
    "date": "2025-05-28",
    "time": "03:45",
    "accountNo": "ACC1015",
    "area": "Galle",
    "supervisor": "D",
    "teamNo": "2",
    "helper": "B",
    "dc": false,
    "rc": true,
    "payment100": true,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": true,
    "billingError": false,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "17",
    "date": "2025-06-08",
    "time": "04:00",
    "accountNo": "ACC1016",
    "area": "Kurunagala",
    "supervisor": "B",
    "teamNo": "1",
    "helper": "D",
    "dc": false,
    "rc": false,
    "payment100": true,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": false,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": true,
    "billingError": true,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "18",
    "date": "2025-06-08",
    "time": "04:15",
    "accountNo": "ACC1017",
    "area": "Galle",
    "supervisor": "C",
    "teamNo": "2",
    "helper": "D",
    "dc": false,
    "rc": true,
    "payment100": false,
    "payment80": true,
    "payment50": true,
    "alreadyPaid": true,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": true,
    "billingError": false,
    "cantFind": true,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "19",
    "date": "2025-06-08",
    "time": "04:30",
    "accountNo": "ACC1018",
    "area": "JaEla",
    "supervisor": "A",
    "teamNo": "1",
    "helper": "D",
    "dc": false,
    "rc": false,
    "payment100": true,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "20",
    "date": "2025-06-08",
    "time": "04:45",
    "accountNo": "ACC1019",
    "area": "JaEla",
    "supervisor": "B",
    "teamNo": "3",
    "helper": "C",
    "dc": false,
    "rc": false,
    "payment100": true,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "21",
    "date": "2025-06-08",
    "time": "05:00",
    "accountNo": "ACC1020",
    "area": "JaEla",
    "supervisor": "C",
    "teamNo": "2",
    "helper": "D",
    "dc": true,
    "rc": false,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": false,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": true,
    "billingError": false,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "22",
    "date": "2025-06-08",
    "time": "05:15",
    "accountNo": "ACC1021",
    "area": "Galle",
    "supervisor": "A",
    "teamNo": "3",
    "helper": "B",
    "dc": true,
    "rc": false,
    "payment100": true,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": true,
    "billingError": false,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "23",
    "date": "2025-06-08",
    "time": "05:30",
    "accountNo": "ACC1022",
    "area": "Kurunagala",
    "supervisor": "C",
    "teamNo": "1",
    "helper": "D",
    "dc": true,
    "rc": true,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": true,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "24",
    "date": "2025-06-08",
    "time": "05:45",
    "accountNo": "ACC1023",
    "area": "JaEla",
    "supervisor": "C",
    "teamNo": "3",
    "helper": "C",
    "dc": false,
    "rc": false,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": false,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "25",
    "date": "2025-06-08",
    "time": "06:00",
    "accountNo": "ACC1024",
    "area": "Galle",
    "supervisor": "B",
    "teamNo": "1",
    "helper": "D",
    "dc": true,
    "rc": false,
    "payment100": false,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "26",
    "date": "2025-06-08",
    "time": "06:15",
    "accountNo": "ACC1025",
    "area": "Galle",
    "supervisor": "C",
    "teamNo": "3",
    "helper": "C",
    "dc": true,
    "rc": false,
    "payment100": true,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": false,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "27",
    "date": "2025-06-08",
    "time": "06:30",
    "accountNo": "ACC1026",
    "area": "Kurunagala",
    "supervisor": "A",
    "teamNo": "2",
    "helper": "D",
    "dc": false,
    "rc": false,
    "payment100": false,
    "payment80": false,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": true,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": false,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "28",
    "date": "2025-05-20",
    "time": "06:45",
    "accountNo": "ACC1027",
    "area": "JaEla",
    "supervisor": "B",
    "teamNo": "2",
    "helper": "B",
    "dc": true,
    "rc": false,
    "payment100": false,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": false,
    "unSolvedCusComp": false,
    "gateClosed": false,
    "meterRemoved": true,
    "alreadyDisconnected": true,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": false,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "29",
    "date": "2025-05-20",
    "time": "07:00",
    "accountNo": "ACC1028",
    "area": "Galle",
    "supervisor": "D",
    "teamNo": "1",
    "helper": "B",
    "dc": false,
    "rc": true,
    "payment100": false,
    "payment80": false,
    "payment50": true,
    "alreadyPaid": true,
    "unSolvedCusComp": true,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": true,
    "wrongMeter": false,
    "billingError": false,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": false,
    "photo": "/placeholder.svg?height=100&width=100"
  },
  {
    "id": "30",
    "date": "2025-05-20",
    "time": "07:15",
    "accountNo": "ACC1029",
    "area": "JaEla",
    "supervisor": "A",
    "teamNo": "2",
    "helper": "C",
    "dc": false,
    "rc": true,
    "payment100": true,
    "payment80": true,
    "payment50": false,
    "alreadyPaid": true,
    "unSolvedCusComp": false,
    "gateClosed": true,
    "meterRemoved": false,
    "alreadyDisconnected": false,
    "wrongMeter": false,
    "billingError": true,
    "cantFind": true,
    "objections": true,
    "stoppedByNWSDB": true,
    "photo": "/placeholder.svg?height=100&width=100"
  }
];